language: java
services:
  - mysql

test:
  adapter: mysql2
  database: hello
  username: root
  encoding: utf8
  
before_install:
  - mysql -e '<CREATE DATABASE hello;
USE hello;
CREATE TABLE contact ( id int(11) NOT NULL AUTO_INCREMENT, name varchar(255) DEFAULT NULL, PRIMARY KEY (id) ) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;
INSERT INTO hello.contact (name) VALUES ('first');
INSERT INTO hello.contact (name) VALUES ('second');>'

